### ISSUE TITLE
`npm run build` throws warnings and errors

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#202]
The build throws several warnings and errors, then fails completely.

```
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'components/accordion'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'components/accordion'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at LastSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)'
HeadlessChrome 65.0.3325 (Windows 10.0.0): Executed 0 of 134 SUCCESS (0 secs / 0 secs)
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'components/accordion'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'components/accordion'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at LastSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)'
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'components/accordion'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'components/accordion'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'styles/chart'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'styles/chart'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at LastSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)'
HeadlessChrome 65.0.3325 (Windows 10.0.0): Executed 16 of 134 SUCCESS (0 secs / 0.787 secs)
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'styles/chart'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'styles/chart'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at LastSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)'
ERROR: 'Unhandled Promise rejection:', 'Cannot match any routes. URL Segment: 'styles/chart'', '; Zone:', 'angular', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Cannot match any routes. URL Segment: 'styles/chart'
    at ApplyRedirects.webpackJsonp../node_modules/@angular/router/esm5/router.js.ApplyRedirects.noMatchError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1765:1)
    at CatchSubscriber.selector (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/router/esm5/router.js:1730:1)
    at CatchSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/catchError.js.CatchSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/operators/catchError.js:105:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:134:1)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/Subscriber.js:108:1)
```
...
```
npm WARN @healthcatalyst/cashmere@0.0.6 requires a peer of npm-font-open-sans@^1.1.0 but none is installed. You must install peer dependencies yourself.
```
...
```
'QueryList' is imported from external module '@angular/core' but never used
```
...
```
No name was provided for external module 'popper.js' in options.globals – guessing 'Popper'
```
...
```
Dropping unreachable code [0:324,8]
Declarations in unreachable code! [0:324,8]
Dropping unreachable code [0:693,8]
Declarations in unreachable code! [0:693,8]
```
...
```
@angular/compiler-cli@5.2.9 requires typescript@'>=2.4.2 <2.7.0' but 2.8.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```
...
```
ERROR in ..\lib\src\button\button.module.ts(9,2): Error during template compile of 'ButtonModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
```

**Comment by joeskeen** [comment]
> `npm WARN @healthcatalyst/cashmere@0.0.6 requires a peer of npm-font-open-sans@^1.1.0 but none is installed. You must install peer dependencies yourself.`

@isaaclyman you can fix this by running `npm i --save npm-font-open-sans`

**Comment by isaaclyman** [comment]
It looks like open sans is optional--is there a reason it's a peer dependency? This may lead users to believe it's required.

**Comment by joeskeen** [comment]
I am aware of some of these warnings, but I'm able to build without errors.  Would you like to set up a call to walk through this and resolve the issues you are seeing?

**Comment by isaaclyman** [comment]
Just to make sure we're on the same page first, are you building from the latest version of `master`?

**Comment by joeskeen** [comment]
Yes.  Just to confirm, I recloned the repository from scratch, ran `npm i`, and `ng build` and it completed successfully.  Also, you can see on the repository's home page that the build is passing in Travis CI: https://travis-ci.org/HealthCatalyst/Fabric.Cashmere/branches

```
joeskeen@HC2370 /mnt/c/Source/sandbox/temp
$ git clone git@github.com:HealthCatalyst/Fabric.Cashmere.git
Cloning into 'Fabric.Cashmere'...
Enter passphrase for key '/home/joeskeen/.ssh/id_rsa':
remote: Counting objects: 4880, done.
remote: Total 4880 (delta 0), reused 0 (delta 0), pack-reused 4879
Receiving objects: 100% (4880/4880), 7.21 MiB | 85.00 KiB/s, done.
Resolving deltas: 100% (3379/3379), done.
Checking connectivity... done.
Checking out files: 100% (343/343), done.

joeskeen@HC2370 /mnt/c/Source/sandbox/temp
$ cd Fabric.Cashmere/

joeskeen@HC2370 /mnt/c/Source/sandbox/temp/Fabric.Cashmere (master)
$ npm i

> node-sass@4.8.3 install /mnt/c/Source/sandbox/temp/Fabric.Cashmere/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/joeskeen/.npm/node-sass/4.8.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /mnt/c/Source/sandbox/temp/Fabric.Cashmere/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.8.3 postinstall /mnt/c/Source/sandbox/temp/Fabric.Cashmere/node_modules/node-sass
> node scripts/build.js

Binary found at /mnt/c/Source/sandbox/temp/Fabric.Cashmere/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN @healthcatalyst/cashmere-docs@0.0.6 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1330 packages from 1492 contributors in 199.881s

joeskeen@HC2370 /mnt/c/Source/sandbox/temp/Fabric.Cashmere (master)
$ ng build

@angular/compiler-cli@5.2.9 requires typescript@'>=2.4.2 <2.7.0' but 2.8.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

Date: 2018-04-16T21:31:11.625Z
Hash: d2ca73e586e3dddeb992
Time: 80145ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 966 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 275 kB [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 19.2 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 92.3 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.52 MB [initial] [rendered]

joeskeen@HC2370 /mnt/c/Source/sandbox/temp/Fabric.Cashmere (master)
$
```

**Comment by joeskeen** [comment]
Here are my tools versions:

```
C:\Source\sandbox\temp\Fabric.Cashmere>node -v
v8.9.3

C:\Source\sandbox\temp\Fabric.Cashmere>npm -v
5.8.0

C:\Source\sandbox\temp\Fabric.Cashmere>ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript-formatter: 7.0.1
typescript: 2.8.1
webpack: 3.11.0

C:\Source\sandbox\temp\Fabric.Cashmere>
```

**Comment by jtrujill** [comment]
When I run `npm run build:lib` it completes fine but when I run `npm run build:demo` I get the following
`ERROR in ../lib/src/button/button.module.ts(9,2): Error during template compile of 'ButtonModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.`

**Comment by joeskeen** [comment]
For normal library development, you should only need to run `ng serve`.  You should only need to run `npm run build:lib` if you are doing an NPM package build.  As a part of that process, it installs the subset of packages that are needed for the library in the `lib` folder.  If you have run that already and want to run the demo again, you need to remove the `lib/node_modules` folder.  In the future we can add a `clean` command for that, but as I said, normally you won't need to run the lib build.

**Comment by joeskeen** [comment]
That is interesting.  I have never tried that command, but it seems that it is fundamentally flawed:

`"build": "npm run build:lib && npm run build:demo",`

As I mentioned before, you can't run the Demo build right after the lib build.  I'll have to fix that.  For now, though, just use `ng build`.
